# Generated by Django 5.2 on 2025-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MED', 'Media'), ('HIGH', 'Alta')], default='MED', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('IP', 'En progreso'), ('COM', 'Completada')], default='PEN', max_length=3),
        ),
    ]
