# Generated by Django 5.2 on 2025-05-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0003_alter_task_due_date_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('urgente_importante', 'Urgente e Importante'), ('urgente_no_importante', 'Urgente y No Importante'), ('no_urgente_importante', 'No Urgente, pero Importante'), ('no_urgente_no_importante', 'No Urgente y No Importante')], default='no_urgente_importante', max_length=30),
        ),
    ]
